### ISSUE TITLE
A test issue 

### ISSUE THREAD

**Issue by mbaker21231** [mbaker21231/PhdTwo#1]
Trying to get issues up and going.

**Comment by mbaker21231** [comment]
Here is a useful trick for sharing ```stata``` code. 
```
getmata (b1*) = b1Hold
getmata (b0*) = b0Hold
getmata (e*) = eHold

gen t = _n
tsset t
tsline e1 e2 e3 e4


```

**Comment by mbaker21231** [comment]
To continue the test - still nothing being posted. Also, I am running into github issues because of a few experiments I did. I'm probably going to have to fix them before setting up a new data set. I will let everyone know.

**Comment by MicaMichela** [comment]
Let's test if I can respond directly from the site.

Thanks for taking the time to meet today. I look forward to working on some more logit models once I get that new data. Let me know if I can help with the data source documentation or data set aggregation.

**Comment by mbaker21231** [comment]
Mica --

Your last comment came in load and clear! And thanks for setting aside the time for meeting - it's exciting to have a team (of two so far, but a team nonetheless!). So, to get updates and allow responses through email, I think you have to go to your account, and then ```Settings -> Notifications``` and then set all the preferences around ```Autowatching``` and all that. I basically have everything checked off in this area. 

If you get a chance, maybe you can try fiddling around with your account settings and then responding to this email from your email.
