### ISSUE TITLE
Data download ok?

### ISSUE THREAD

**Issue by mbaker21231** [mbaker21231/PhdTwo#2]
Just checking to see if the data download went okay. Here is the link:

https://s3-ap-southeast-1.amazonaws.com/static-web-materials/cityXcountry.csv

Best,

Matt

**Comment by MicaMichela** [comment]
Thanks Matt! It is downloading. I'll let you know when it downloads fully.
May take a few hours.

**Comment by mbaker21231** [comment]
Sure thing - one thing that occurred to me is that the data set might be so huge is because of the (needless) repetition of country geography at every observation. I can't even open it on my work desktop because it has only 4gb RAM! I'm going to see if there is a way to reduce the size of it...

Also, your comment came through on email and showed up here as well!

**Comment by MicaMichela** [comment]
Great news! Data looks good and I am able to open the file with Stata despite its large size. I have some "getting to know the data" questions about our 398 variables. The "Ideas and Data" and "Data Organization" github descriptions already help a lot. 

When we last met, you mentioned that the country level health indicators are from the World Bank and WHO. Is all the city level data from NASA exclusively? 

I see the following city level variables:
'PlaceName', 'Lat', 'Lon', 'Feature', 'Feature Detail', 'Country Code',
       'Country Code 2', 'Unknown', 'Population', 'elevation1',
       'true elevation', 'TZ', 'geometry', 'urbext', 'phosphorus', 'aerosol',
       'nitrogen', 'childpov', 'pasture', 'c0', 'c11', 'c12', 'c21', 'c22',
       'c23', 'c24', 'c31', 'c32', 'c33', 'c34', 'c41', 'c42', 'c43', 'c51',
       'c52', 'c53', 'c54', 'c61', 'c62'

From your notes, the c0-c62 variables are indicator variables (0 or 1) for anthropomorphic biomes. 

What do the "_x" and "_y" indicate?  

The "unknown" variable is numeric. Does it have a definition? 

I noticed the childpov variable repeats the same value for every city in the United Arab Emirates, Albania, Armenia, Bangladesh.. just to name a few countries as I scroll through the data. This might actually be a country level figure for most of the data points.

Thanks!

**Comment by mbaker21231** [comment]
Mica --

The base city level data is actually all from a website called [ geonames](http://www.geonames.org/export/); that is, this site gives a listing of cities, populations, and latitudes and longitudes. All the photo imagery data that I have so far is from [SEDAC](http://sedac.ciesin.columbia.edu/). The IPython workbooks actually match up cities to points in space, and also aggregate the SEDAC data to the country level. 

The "_x" and "_y" indicate data are really artifacts of merging the data in Python - if observations have the same name in both data sets, Python affixes an _x to the left-hand and a _y to the right hand data set. That doesn't really explain anything about the variables themselves, so I will have to take a look to put together more information.

The child poverty data is an example of data that I was including for verification purposes, as it is a mix of country and smaller-area data (i.e., by the province level in India I think). Thus, it isn't really disaggregated like the SEDAC data is. 

I hope all of that helps!

Matt

**Comment by mbaker21231** [comment]
Hopefully we are all set with this...I'm going to close it.
